---
title: "R Utility Functions"
output:
  html_document:
    df_print: paged
---

# In-built mtcars dataset will be used for visualization dataset. (a glimpse of the dataset)

```{r}
library(knitr)
library(ggplot2)
data("mtcars")
kable(mtcars, caption = "Preview of the dataset")

```

# Selection of colors for categorical and continous variables
 - categorical variables
    - general use
    - advanced use
 - continuous variables
    - general use
    
### categorical variables

```{r}
source("../R/ggplot2_utils/colors_utils.R")

# order the categorical variables
mtcars$cyl = factor(mtcars$cyl, levels = c(4,6,8))
n_cyl = length(levels(mtcars$cyl))

# selection of colors based on different parameters
colors = get_categorical_colors(n = n_cyl,
                                method = 'auto',
                                colorblind_safe = TRUE)
names(colors) = levels(mtcars$cyl)
preview_colors(colors, labels = names(colors))
ggplot(mtcars, aes(x = mpg, y = wt, color = factor(cyl))) +
    geom_point(size = 3) +
    scale_color_manual(values = colors) +
    theme_minimal()


colors = get_categorical_colors(n = n_cyl,
                                method = 'brewer',
                                palette = 'Dark2')
names(colors) = levels(mtcars$cyl)
preview_colors(colors, labels = names(colors))
ggplot(mtcars, aes(x = mpg, y = wt, color = factor(cyl))) +
    geom_point(size = 3) +
    scale_color_manual(values = colors) +
    theme_minimal()



colors = get_categorical_colors(n = 20,
                                method = 'auto')
preview_colors(colors)



```



```{r}
source("../R/ggplot2_utils/colors_utils.R")

# order the categorical variables
mtcars$brand = rownames(mtcars)
mtcars$brand = factor(mtcars$brand)
n_brand = length(levels(mtcars$brand))

# selection of colors based on different parameters
colors = get_publication_colors(n = n_brand,
                                shuffle = TRUE)
names(colors) = levels(mtcars$brand)
preview_colors(colors, labels = names(colors))
ggplot(mtcars, aes(x = mpg, y = wt, color = factor(brand))) +
    geom_point(size = 3) +
    scale_color_manual(values = colors) +
    theme_minimal()

ggplot(mtcars, aes(x = mpg, y = wt, color = factor(brand))) +
    geom_point(size = 3) +
    scale_color_publication() +
    theme_minimal() +
    labs(title = "Publication-Quality Colors")



```

### continous variables

```{r}
source("../R/ggplot2_utils/colors_utils.R")

show_continuous_palettes("publication")
colors = get_continuous_colors(method = "publication", palette = "nature_heatmap")

preview_continuous_colors(colors, values = seq(-1, 1, length.out = 100), 
                          title = "Diverging Scale")
```

# boxplot
```{r}
source('../R/ggplot2_utils/Boxplot.R')
# order the categorical variables
mtcars$cyl = factor(mtcars$cyl, levels = c(4,6,8))
n_cyl = length(levels(mtcars$cyl))

# selection of colors based on different parameters
colors = get_categorical_colors(n = n_cyl,
                                method = 'auto',
                                colorblind_safe = TRUE)
names(colors) = levels(mtcars$cyl)

create_boxplot(mtcars, x_var = "cyl", y_var = "mpg", 
               title = "MPG by Number of Cylinders",
               fill_var = "cyl")+
  boxplot_theme()+scale_fill_manual(values = colors)

complex_boxplot(data=mtcars,
                            x_var='cyl',
                            y_var='mpg',
                            fill_var = 'cyl',
                            facet_var = NULL,
                            facet_type = "wrap",
                            add_violin = FALSE,
                            add_points = TRUE,
                            point_style = "jitter",
                            add_mean = FALSE,
                            error_type = "se",
                            notched = FALSE,
                            add_n_labels = TRUE,
                            add_statistics = TRUE,
                            stat_method = "t.test",
                            stat_comparisons = NULL,
                            title = "MPG by Number of Cylinders",
                            subtitle = NULL,
                            x_label = NULL,
                            y_label = NULL,
                            color_palette = "Set2",
                            alpha_level = 0.7,
                            base_size = 12,
                            legend_position = "right",
                            coord_flip = FALSE,
                            y_limits = NULL,
                            custom_theme = boxplot_theme())+scale_fill_manual(values = colors)
  




```

# scatterplot

```{r}
source("../R/ggplot2_utils/Scatterplot.R")

simple_scatterplot_categorical(data=mtcars,
                    x_var='mpg',
                    y_var='wt',
                    color_var = 'cyl',
                    add_smooth = TRUE,
                    smooth_method = "lm",
                    smooth_se=TRUE,
                    add_correlation = TRUE,
                    smooth_se_group = FALSE,
                    point_alpha = 0.6,
                    point_size = 2.5,
                   custom_theme = scatterplot_theme())+scale_color_manual(values = colors)

simple_scatterplot_continuous(data=mtcars,
                    x_var='mpg',
                    y_var='wt',
                    color_var = 'mpg',
                                size_var = 'wt',
                                add_smooth = TRUE,
                                smooth_method = "lm",
                                color_palette = 'viridis',
                                title = "",
                                point_size = 3.5,
                                point_alpha = 0.7,
                    custom_theme = scatterplot_themea_with_legend_title())


```


### special case for scatterplot -- UMAP

```{r}
source("../R/ggplot2_utils/UMAP_scatterplot.R")

# initiate a toy data
df = data.frame(umap_1 = rnorm(3000, mean=2, sd=1), umap_2 = rnorm(3000, mean=1, sd=1),
                group = paste('CC', sample(0:9,3000, replace=TRUE)),
                feature = rnorm(3000, mean=10, sd=20))
df$feature = df$feature - min(df$feature)

x_min <- min(df$umap_1)
y_min <- min(df$umap_2)
x_max <- max(df$umap_1)
y_max <- max(df$umap_2)

# plot with distinctive colors
plot = ggplot(data = df, aes(x = umap_1, y=umap_2, color=group))+
  geom_point()+
  umap_theme_without_texts()

add_umap_arrows(plot, x_min, x_max, y_min, y_max)

# plot with default gradient colors
plot = ggplot(data = df, aes(x = umap_1, y=umap_2, color=feature))+
  geom_point()+
  umap_theme_without_texts()

add_umap_arrows(plot, x_min, x_max, y_min, y_max)

# plot with customized gradient colors
source("../R/ggplot2_utils/colors_utils.R")
upper = 100
lower = 0
median = (upper+lower)/2

plot = ggplot(data = df, 
           aes(x = umap_1, y=umap_2, 
               color = feature)
)+
  geom_point(alpha = .8, size=3)+
  scale_color_continuous_custom(method = "publication", 
                               palette = "climate",
                               limits = c(lower,upper),
                               breaks = seq(lower,upper,median),
                               oob = function(x, ...){scales::squish(x, c(lower,upper))})+
  umap_theme_without_texts()

add_umap_arrows(plot, x_min, x_max, y_min, y_max)

```


# barplot

```{r}
source("../R/ggplot2_utils/Ridge_Barplot.R")
mtcars$cyl = factor(mtcars$cyl, levels = c(4,6,8))
mtcars$vs = factor(mtcars$vs, levels = c(0,1))
mtcars$gear = factor(mtcars$gear, levels = c(3,4,5))

create_barplot(mtcars, 
               x_var = "cyl", 
               y_var = NULL,
               fill_var = "vs", 
               reorder_bars = FALSE,
               stat_type = "count",
               custom_theme = barplot_clean_theme())

create_barplot(mtcars, 
               x_var = "cyl", 
               y_var = NULL,
               fill_var = "gear", 
               reorder_bars = FALSE,
               stat_type = "count",
               custom_theme = barplot_clean_theme(),
               facet_var = 'vs')


result2 <- quick_percentage(mtcars, "cyl", "gear")
print(result2)

create_barplot(result2, 
               x_var = "cyl", 
               y_var = "percentage",
               fill_var = "gear", 
               reorder_bars = FALSE,
               custom_theme = barplot_clean_theme(),
               stat_type = "prop")

df_facet_barplot = data.frame(cyl=factor(),
                              gear = factor(),
                              percentage = numeric(),
                              vs = factor())
for (i in levels(mtcars[["vs"]])) {
  tmp = mtcars[mtcars[["vs"]] == i,]
  tmp = quick_percentage(tmp, "cyl", "gear")
  tmp["vs"] = i
  df_facet_barplot = rbind(df_facet_barplot, tmp)
}
create_barplot(df_facet_barplot, 
               x_var = "cyl", 
               y_var = "percentage",
               fill_var = "gear", 
               reorder_bars = FALSE,
               custom_theme = barplot_clean_theme(),
               stat_type = "prop",
               facet_var = "vs")


```

# Ridgeplot

```{r}

## you should have multiple values to plot it for each category
## otherwise you get nothing out of it
source("../R/ggplot2_utils/Ridge_Barplot.R")
mtcars$cyl = factor(mtcars$cyl, levels = c(4,6,8))
mtcars$vs = factor(mtcars$vs, levels = c(0,1))
mtcars$gear = factor(mtcars$gear, levels = c(3,4,5))

create_faceted_ridgeplot(data = mtcars,
                         x_var = "wt",
                         y_var = "cyl",
                         group_var = "vs")+
  ridgeplot_clean_theme()

```



